"""
Django settings for barber project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""

import os
from pathlib import Path
import dj_database_url
import environ

# Initialiser django-environ
env = environ.Env(
    DEBUG=(bool, False)
)

# Lire le fichier .env
environ.Env.read_env()

# ====== Paths ======
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ====== Security ======
SECRET_KEY = env('SECRET_KEY', default='django-insecure-&#dx$lvmwm+9&7xs32yw0k+&$2oy7v@8+w!djf0-pwk)8@ca&6')
DEBUG = env('DEBUG', default=False)

ALLOWED_HOSTS = [
    'barber-appointment-system.onrender.com',
    'localhost',
    '127.0.0.1',
    'barber-empty-meadow-5749.fly.dev',
    '*.onrender.com'  # Pour Render
]

# ====== Installed Apps ======
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'reservations',
]

# ====== Middleware ======
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# En développement, ajouter le middleware pour éviter le cache
if DEBUG:
    MIDDLEWARE.insert(1, 'reservations.middleware.NoCacheMiddleware')

# ====== URLs & Templates ======
ROOT_URLCONF = 'barber.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'barber.wsgi.application'

# ====== Database ======
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR}/db.sqlite3'
    )
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ====== Internationalization ======
LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Europe/Paris'
USE_I18N = True
USE_TZ = True

# ====== Static & Media Files ======
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ====== Default Auto Field ======
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ====== Auth Redirects ======
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

# ====== WhiteNoise (Production Static) ======
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ====== Cache Control ======
if DEBUG:
    # En développement, désactiver le cache pour les fichiers statiques
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
