# Generated by Django 5.2.7 on 2025-10-13 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='barber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='reservations.barber', verbose_name='Barbier'),
            preserve_default=False,
        ),
    ]
