# Generated by Django 5.2.7 on 2025-10-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_service_barber'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='clients/', verbose_name='Photo de profil'),
        ),
    ]
